// ActionType.js
//Character
export const CHARACTER_UPDATED = 'CHARACTER_UPDATED';
export const CHARACTER_RESTARTED = 'CHARACTER_RESTARTED';
export const CHARACTER_NAME_SAVED = 'CHARACTER_NAME_SAVED';
//Modal
export const MODAL_TOOGLED = 'MODAL_TOOGLED';
//Game
export const GAME_RESTARTED = 'GAME_RESTARTED'
export const STORY_UPDATED = 'STORY_UPDATED'
