// ActionType.js
export const CHARACTER_SUBMITTED = 'CHARACTER_SUBMITTED';
export const CHARACTER_UPDATED = 'CHARACTER_UPDATED';
export const CHARACTER_RESTARTED = 'CHARACTER_RESTARTED';

export const MODAL_TOOGLED = 'CHARACTER_RESTARTED';
