// ActionType.js
//Character
export const CHARACTER_UPDATED = 'CHARACTER_UPDATED';
export const CHARACTER_RESTARTED = 'CHARACTER_RESTARTED';
export const CHARACTER_NAME_SAVED = 'CHARACTER_NAME_SAVED';
//Modal
export const MODAL_TOOGLED = 'MODAL_TOOGLED';
//Game
export const POSITION_UPDATED = 'POSITION_UPDATED'
